import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Hero } from 'components/Hero/Hero'
import { SliderData } from 'components/Hero/SliderData'
import Slider from 'components/Hero/Slider'
import Instagram from 'components/Hero/Instagram'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>Photograph WB DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero heading='Diego Photography' message='All pictures always tell a new story'/>
      <Slider slides={SliderData}/>
      <Instagram />
      </div>
    </>
  )
}
